AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for TeacherFunction and StudentFunction

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: dotnetcore3.1
    MemorySize: 256
    Timeout: 30

Resources:
  TeacherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: ../TeacherFunction/src/TeacherFunction/
      Handler: TeacherFunction::TeacherFunction.Function::Handler
      FunctionName: quizx-query-test
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /quiz/{quizid}
            Method: get
            RestApiId:
              Ref: QuizXApiGateway
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - QuizXWriteDynamoDB

  StudentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../StudentFunction/src/StudentFunction/
      Handler: StudentFunction::StudentFunction.Function::Handler
      FunctionName: quizx-answer-test
      PackageType: Zip
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /quiz/
            Method: post
            RestApiId:
              Ref: QuizXApiGateway
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - QuizXWriteDynamoDB


  QuizXApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test


  QuizXTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: QuizX-test
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: quizId
          AttributeType: S
        - AttributeName: studentId
          AttributeType: S
      KeySchema:
        - AttributeName: quizId
          KeyType: HASH
        - AttributeName: studentId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

